apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen       80;
      server_name  dogs.test;
      root   /usr/share/nginx/html;
      location / {
        add_header x-debug-uri-header "here" always;
        index index.php;
      }
      location ~ \.php$ {
          # add_header x-debug-header "$document_root$fastcgi_script_name" always;
          fastcgi_pass   127.0.0.1:9000;
          fastcgi_index  index.php;
          fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include        fastcgi_params;
      }
    }
