apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  labels:
    app: weather
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: localhost:5001/weather-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice
  labels:
    app: dice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dice
  template:
    metadata:
      labels:
        app: dice
    spec:
      containers:
      - name: dice
        image: localhost:5001/dice-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-metadata
  labels:
    app: pod-metadata
spec:
  replicas: 6
  selector:
    matchLabels:
      app: pod-metadata
  template:
    metadata:
      labels:
        app: pod-metadata
    spec:
      containers:
      - name: pod-metadata
        image: localhost:5001/pod-metadata-app:latest
        env:
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dogs
  template:
    metadata:
      labels:
        app: dogs
    spec:
      initContainers:
        - name: init-php
          image: localhost:5001/dogs-app:latest
          command: [ "/bin/sh", "-c" ]
          args: ["mkdir -p /shared && cp -r /var/www/* /shared && chown -R www-data:www-data /shared/html && ls -la /shared/html"]
          volumeMounts:
            - name: shared-files
              mountPath: /shared
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-files
              mountPath: /usr/share/nginx/html
              subPath: html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
        - name: php-fpm
          image: localhost:5001/dogs-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html
              subPath: html
      volumes:
        - name: shared-files
          emptyDir: {}

        - name: nginx-config
          configMap:
            name: nginx-config
